In [1]:
from google.colab import drive
drive.mount('drive')

Mounted at drive


In [4]:
%cd /content/drive/MyDrive/DATN

/content/drive/MyDrive/DATN


In [ ]:
!python3 test.py --iter 03500


Initialzing...
Initializing data source...
Traceback (most recent call last):
  File "/content/drive/MyDrive/DATN/test.py", line 35, in <module>
    m = initialization(conf, test=opt.cache)[0]
  File "/content/drive/MyDrive/DATN/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/content/drive/MyDrive/DATN/model/initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "/content/drive/MyDrive/DATN/model/utils/data_loader.py", line 25, in load_data
    seqs = os.listdir(_seq_dir)
KeyboardInterrupt
^C


In [ ]:
!python3 train.py


python3: can't open file '/content/train.py': [Errno 2] No such file or directory


In [ ]:
!python3 test.py --iter 03600


Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 3600...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:00:22.983389
===Rank-1 (Include identical-view cases)===
NM: 86.157,	BG: 85.640,	CL: 65.393
===Rank-1 (Exclude identical-view cases)===
NM: 84.886,	BG: 84.318,	CL: 64.091
===Rank-1 of each angle (Exclude identical-view cases)===
NM: [81.25 92.50 92.50 83.75 71.25 91.25 91.25 83.75 86.25 85.00 75.00]


In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
Traceback (most recent call last):
  File "/content/drive/MyDrive/DATN/train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/content/drive/MyDrive/DATN/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/content/drive/MyDrive/DATN/model/initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "/content/drive/MyDrive/DATN/model/utils/data_loader.py", line 25, in load_data
    seqs = os.listdir(_seq_dir)
KeyboardInterrupt
^C


In [ ]:
!python3 test.py --iter 7000

Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 7000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:11:18.065202
===Rank-1 (Include identical-view cases)===
NM: 85.331,	BG: 85.434,	CL: 68.388
===Rank-1 (Exclude identical-view cases)===
NM: 83.977,	BG: 84.091,	CL: 67.045
===Rank-1 of each angle (Exclude identical-view cases)===
NM: [80.00 88.75 90.00 85.00 71.25 87.50 90.00 81.25 87.50 81.25 81.25]


In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/c

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['020', '021', '022', '023'], ['024', '025']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['020', '021', '022', '023']) list(['024', '025'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or 

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['021', '022', '023'], ['024', '025']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['021', '022', '023']) list(['024', '025'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running s

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['020', '021', '022', '023'], ['024', '025']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['020', '021', '022', '023']) list(['024', '025'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLo

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['016', '017', '018', '019'], ['020', '021']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['016', '017', '018', '019']) list(['020', '021'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLo

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['001', '002', '003', '004', '006', '007', '008', '009', '010'], ['011', '012', '013', '014', '015', '016']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['001', '002', '003', '004', '006', '007', '008', '009', '010'])
 list(['011', '012', '013', '014', '015', '016'])]
Loading training data...
Traceback (most recent call last):
  File "/content/drive/MyDrive/DATN/train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/content/drive/MyDrive/DATN/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/cont

In [ ]:
!python3 train.py


Initialzing...
Initializing data source...
pid_list: [['001', '002', '003', '004', '006', '007', '008', '009', '010'], ['011', '012', '013', '014', '015', '016']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['001', '002', '003', '004', '006', '007', '008', '009', '010'])
 list(['011', '012', '013', '014', '015', '016'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2,

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_list: [['001', '002', '003', '004', '006', '007', '008', '009', '010'], ['011', '012', '013', '014', '015', '016']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['001', '002', '003', '004', '006', '007', '008', '009', '010'])
 list(['011', '012', '013', '014', '015', '016'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2,

In [ ]:
!python3 train.py

Initialzing...
Initializing data source...
pid_fname existed: partition/CASIA-B_9_False.npy
all_pid_list: ['001', '002', '003', '004', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025']
pid_list: [list(['001', '002', '003', '004', '006', '007', '008', '009', '010'])
 list(['011', '012', '013', '014', '015', '016'])]
not_train_list: ['019', '022', '023', '021', '025', '024', '018', '017', '020']
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [['019', '022', '023', '021', '025', '024', '018', '017', '020'], ['011', '012', '013', '014', '015', '016']]
Loading training data...
Data initia

In [ ]:
!python3 test.py --iter 18000

Initialzing...
pid_list: [['020', '021', '022', '018', '024', '019', '017', '025', '023'], ['011', '012', '013', '014', '015', '016']]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 18000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:18:24.145086
===Rank-1 (Include identical-view cases)===
NM: 83.540,	BG: 79.270,	CL: 68.733
===Rank-1 (Exclude identical-view cases)===
NM: 81.894,	BG: 77.727,	CL: 67.045
===Rank-1 of each angle (Exclude iden

In [ ]:
!python3 train.py

Initialzing...
pid_list: [['001', '002', '003', '004'], ['006', '007', '008']]
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [list(['001', '002', '003', '004']) list(['006', '007', '008'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running s

In [ ]:
!python3 test.py --iter 10000

Initialzing...
pid_fname existed: partition/CASIA_4_False.npy
all_pid_list: ['001', '002', '003', '004', '006', '007', '008']
pid_list: [list(['001', '002', '003', '004']) list(['006', '007', '008'])]
not_train_list: []
/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)
pid_list: [[], ['006', '007', '008']]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoade

In [ ]:
!python3 test.py --iter 10000



Initialzing...
pid_list: [list(['001', '002', '003', '004', '006', '007', '008', '009', '010'])
 list(['011', '012', '013', '014', '015', '016'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:18:52.708603
===Rank-1 (Include identical-view cases)===
NM: 84.229,	BG: 72.865,	CL: 59.160
===Rank-1 of each angle (Include identical-view cases)===
NM: [75.76 85.61 75.76 82.58 87.12 91.67 91.67

In [ ]:
!python3 test.py --iter 18000

Initialzing...
pid_list: [['020', '021', '022', '018', '024', '019', '017', '025', '023'], ['011', '012', '013', '014', '015', '016']]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 18000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:00:29.774708
===Rank-1 (Include identical-view cases)===
NM: 83.540,	BG: 79.270,	CL: 68.733
===Rank-1 of each angle (Include identical-view cases)===
NM: [84.09 79.55 75.76 77.27 84.85 84.09 84.09 85.61 87.88

In [ ]:
!python3 test.py --iter 18000

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
 [ 8 10 13 14 15 12  9 11  3  1  0  2 19 22 20 18 17 21 16 23  6  7  4  5]
 [15 12 14 13  8 11 10  1  0  3  9  2 19 22 18 20 17 16 21 23  6  7  4  5]
 [14 15 13 12  8  1  3 10  0 11  2  9 19 18 22 20 17 21 23 16  6  7  4  5]
 [19 18 17 16 12 11 10 22 15 13  8 20 14  9  0  1 21  3 23  2  6  7  5  4]
 [19 18 17 22 16 20 21 23 12 15 14 13 10  8  9  0 11  1  5  3  6  4  7  2]
 [23 21 22 20  6  7  5  4 18 19 17  3 12  0  2  1 15 16 14 10 13 11  9  8]
 [23 21 22 20  6  7  4  5 18 19 17 12  3  0  2 15  1 14 10 13 16  9  8 11]]
gallery_y: ['011' '011' '011' '011' '012' '012' '012' '012' '013' '013' '013' '013'
 '014' '014' '014' '014' '015' '015' '015' '015' '016' '016' '016' '016']
probe_y: ['011' '011' '012' '012' '013' '013' '014' '014' '015' '015' '016' '016']
idx: [[12 11 14 13  0 15  3  9  8  1  2 10 18 19 17 16 23 22 21 20  5  7  4  6]
 [14 12 15 11 13  0  3  2  9  1  8 10 18 19 16 17 22 23 21 20  5  7  4  6]
 [ 7  4  6  5 20 23 2

In [ ]:
!python3 test.py --iter 18000

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
 [ 7  5  4  6 23 20 22 21 19 18 16 17 10 13  8 15  3 14  0  2  9  1 11 12]
 [ 5  4  6 20  7 23 22 21 19 18 16 17 10 13  8 14 15  9  3  0 11  2  1 12]
 [ 8 11  9 14  3 10  0  1 15 13  2 12 18 16 19 17 20  6 22 23  4  5  7 21]
 [11  9  8  1  3 12 15  2  0 10 13 14 18 16 19 17 20  6 22 23  5  4  7 21]
 [10 11  0  1  8  3 15  2  9 13 14 12 20  6 22 18 23 19 16  5  4  7 17 21]
 [10  1 11  0 15  8  3 13  2  9 12 14 20 18  6 19 22 23 16  7  5  4 17 21]
 [19 16 18 17 20  6 23  7  4  5 10 22  8  9 21 15 11 13 12  3  1  2  0 14]
 [18 16 19 17 10  1 12  3 15  9 20 11  2  8 13  0 14 23  6 22  7  5  4 21]
 [ 8  6 10 20  9 11 19 13  3 14 15 16 18  4  1 17 23  2  0 12  5 22  7 21]
 [20  6  8 19  4 23 16 10  5  9 18 22 11 17  7  3 13 15 14  2  1 21 12  0]]
p: 2
gallery_y[idx[:, 0:num_rank]: [['011' '011' '011' '013' '014']
 ['011' '011' '011' '014' '014']
 ['012' '012' '012' '012' '016']
 ['012' '012' '012' '016' '012']
 ['013' '013' '013' '014'

In [ ]:
!python3 test.py --iter 10000

Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['005', '006', '007'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
/content/drive/MyDrive/DATN/model/utils/evaluator.py:46: RuntimeWarning: invalid value encountered in true_divide
  np.sum(np.cumsum(np.reshape(probe_y, [-1, 1]) == gallery_y[idx[:, 0:num_rank]], 1) > 0,
Evaluation complete. Cost: 0:00:42.125836
===Rank-1 (Include identical-view ca

In [ ]:
!python3 test.py --iter 10000

Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['005', '006', '007'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:00:43.774361
===Rank-1 (Include identical-view cases)===
NM: 76.585,	BG: 76.585,	CL: 76.585
===Rank-1 of each angle (Include identical-view cases)===
NM: [60.61 60.61 84.85 90.91 81.82 78.79 87.88 75.76 90.91 57.58 72.73]
BG: [60.61 60.61 84.85 90.91 81

In [ ]:
!python3 test.py --iter 10000


Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['005', '006', '007'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:00:42.567433
===Rank-1 (Include identical-view cases)===
NM: 84.299,	BG: 73.555,	CL: 78.789
===Rank-1 of each angle (Include identical-view cases)===
NM: [87.88 93.94 87.88 84.85 84.85 75.76 81.82 90.91 90.91 72.73 75.76]
BG: [60.61 51.51 81.82 87.88 81

In [ ]:
!python3 train.py

Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['006', '007', '008'])]
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
1 restore_iter: {} 0
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/content/drive/MyDrive/DATN/model/network/triplet.py:22: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/IndexingUtils.h:27.)
  hard_hp_dist = torch.max(torch.masked_select(dist, hp_mask)

In [ ]:
!python3 test.py --iter 4600

Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['006', '007', '008'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 4600...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:08:46.327520
===Rank-1 (Include identical-view cases)===
NM: 59.780,	BG: 47.934,	CL: 54.821
===Rank-1 of each angle (Include identical-view cases)===
NM: [45.45 33.33 54.54 60.61 72.73 69.70 69.70 63.64 75.76 57.58 54.55]
BG: [15.15 36.36 51.51 66.67 69.

In [5]:
!python3 test.py --iter 6700

Initialzing...
pid_list: [list(['001', '002', '003', '004']) list(['006', '007', '008'])]
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 6700...
Transforming...
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 3 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Evaluating...
Evaluation complete. Cost: 0:06:23.868174
===Rank-1 (Include identical-view cases)===
NM: 63.361,	BG: 52.892,	CL: 59.780
===Rank-1 of each angle (Include identical-view cases)===
NM: [51.51 30.30 60.61 54.55 78.79 75.76 69.70 78.79 84.85 60.61 51.52]
BG: [36.36 36.36 42.42 75.76 81.